[tool.poetry]
name = "archange"
version = "1.0.0"
description = "Argentine Exchange Rates API â€“ fetch, store and serve ARS exchange rates"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
